### ISSUE TITLE
Security group on drawing

### ISSUE THREAD

**Issue by crdotson** [ibm-cloud-architecture/ibm-cloud-stencils#1]
visio2013/templates/ibm_vpc_architecture.vstx shows a security group as a dotted line around all VSIs in two different subnets, but a security group actually applies to individual VSIs.  Wouldn't it be better to show a security group dotted line around each individual VSI with some note that the default rule allows all communications between VSIs in the same security group?  Like https://console.bluemix.net/docs/infrastructure/vpc/security-groups.html#using-security-groups-in-ibm-cloud-vpc-beta .

As pictured it's not wrong, just a little confusing.

**Comment by jaywarfield** [comment]
@crdotson Yes and each VSI can have multiple vNICs where each vNIC could have different multiple security groups applied and each vNIC could be attached to a different subnet where each subnet could have a different ACL applied.  The provided VPC template shows several VSIs in the subnet+ACL of their primary vNIC and one security group for their primary vNIC where the security group spans tiers across subnets to help show at-a-glance what VSIs that security group covers for the primary vNICs, following the example here: [https://console.bluemix.net/docs/infrastructure/vpc/vpc-regions-and-subnets.html#using-an-ibm-cloud-vpc-with-regions-and-subnets](url)

The provided VPC template is an example to customize as desired but can always be updated to whatever would be the most useful.

Thanks!

**Comment by jaywarfield** [comment]
Will close out this issue after further discussion but will continue to consider what would be the most useful basic template to visualize VPC features in a diagram in addition to reference architectures.  
Thank you for using IBM Cloud!
