### ISSUE TITLE
Cloud stencil for Lucid Chart

### ISSUE THREAD

**Issue by vchouhan** [ibm-cloud-architecture/ibm-cloud-stencils#17]
Will there be support for Lucid charts in the near future? I tried to use the draw.io and ran into issues importing some in Lucid chart. The images are not exported from Draw.io to Lucid charts. 

I was not able to import these into Lucid.
ibm_vpc_frontend_backend_architecture.drawio
ibm_vpc_floating_ip_architecture.drawio
ibm_vpc_architecture_simple.drawio

Also, is there a library of IBM Cloud solution available for Lucid Charts?
example of AWS library on Ludid.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/1222739/130369721-eff22bd0-f70e-4df9-9727-76b34d0e7b74.png">

**Comment by jaywarfield** [comment]
Hi Vishwas, no plans at this time for Lucidchart but looks good, we should make a note of your request.  Thanks for choosing IBM Cloud!
