### ISSUE TITLE
Should ibm_vpc_architecture.xml file be an xml file??

### ISSUE THREAD

**Issue by markpokane** [ibm-cloud-architecture/ibm-cloud-stencils#2]
Just curious as the rest are powerpoint :)

**Comment by markpokane** [comment]
And excuse my manners... thanks for sharing these Jay... very helpful  :). The "microsoft-architecture-diagram-5-updated.pptx" file returns an error when I try to open it? Should it be opne-able in ppt? Not sure what a ppt stencil is.

**Comment by jaywarfield** [comment]
@markpokane That xml file is for the draw.io version - thanks for letting me know that it was in the wrong folder which I just corrected.  I downloaded and opened the microsoft-architecture-diagram-5-updated.pptx from github without an error on Mac and Windows 10.  The files won't display within the browser I'm using with github saying the files are too big to display.  Please try again.  Stencils contains the icons that can be used to create diagrams.  A template is a diagram example that has been created from those stencils.  Thank you for choosing IBM Cloud!

**Comment by markpokane** [comment]
Cheers Jay
