### ISSUE TITLE
Cannot find the VPC architecture template

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-architecture/ibm-cloud-stencils#3]
@jaywarfield Where do I find this template?
https://github.com/ibm-cloud-architecture/ibm-cloud-stencils/blob/master/images/ibm_vpc_architecture_power_drawio.png

I was expecting to find a drawio file for this template I could load in draw.io.

**Comment by jaywarfield** [comment]
@lionelmace The same version of that vpc template under Cloud on draw.io is outdated.  I'm recreating the one in the screenshot from scratch to further validate the updated stencils and plan to make available on this github today if possible.  Thanks!

**Comment by lionelmace** [comment]
@jaywarfield Great! Keep me posted. I would like to re-use with a client this Friday morning CET.

**Comment by jaywarfield** [comment]
I put it under drawio/templates, this is the x86 version only, the screenshot is the x86+Power version, I will add the template for x86+Power to match the screenshot and put it in drawio/templates shortly.  Sounds good for a client mtg!

**Comment by jaywarfield** [comment]
Power version template is now there as well as simple version and a glb template.
