### ISSUE TITLE
Icons library should provide the image from the Catalog

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-architecture/ibm-cloud-stencils#4]
Icons library should provide the image from the Catalog https://cloud.ibm.com/catalog

Here is an example for Sysdig icon from the Cloud Catalog in to Draw.io
![image](https://user-images.githubusercontent.com/12241613/73935580-22fbf300-48e1-11ea-90f0-a0201cd1349c.png)

@jaywarfield

**Comment by jaywarfield** [comment]
Agree, that is in process by another team, thanks!
